93 partnership
PEW35MINISTRY/mobile pull request #12
Opened 2024-04-26 02:10 UTC by bohnerjosh

Hey Ethan,

Got the partnership features ready for testing and merging. 

FirstSignIn -> First page user will see when they sign up.
This screen pulls up ProfileImageSettings and PartnerSettings.

PartnerSettings shows users on 3 different lists depending on their status.

Other items:

- Fixed broken search link in CircleSearch
- Refactored reducers in Redux-store to reflect changes made to circle properties in userProfile
- minor refactor in CircleList and CircleDisplay related to the changed reducers
- Added SelectSlider prop. The source package includes both a single slider and range slider.
- Added menu button on CircleDisplay page so that finding Circle-related settings is easier

Let me know what you think.

2024-04-26 04:10 UTC, ethanjohnsrud requested changes
Code's really good, these are design ideas.  Open to further discussion, let me know.

2024-04-26 04:10 UTC, ethanjohnsrud commented on src/1-Profile/Edit-Profile.tsx
> +              text={"Partner Settings"}
"Partnerships"

2024-04-26 04:10 UTC, ethanjohnsrud commented on src/1-Profile/Edit-Profile.tsx
> +  //position: "absolute",
Let's clean up these comments.
Also, `backButton` will be on nearly every page, can we abstract the styling and maybe implementation too?

2024-04-26 04:13 UTC, bohnerjosh commented on src/Widgets/FormInput/FormInput.tsx
> +                    if (field instanceof InputRangeField) {
I'm not sure what you mean. I have to have the instanceof check to get access to the minValue and maxValue props of the InputRangeField.

2024-04-26 04:14 UTC, bohnerjosh commented on src/4-Partners/PartnerSettings.tsx
> +        GET_PendingPartners();
these should satisfy my TODO. The useEffect is formatted such that this will only be called once on component load.

2024-04-29 00:57 UTC, bohnerjosh commented on src/widgets.tsx
> +
I can change it to be cased

2024-04-29 04:16 UTC, ethanjohnsrud requested changes
Thanks for making the tweaks, a few more renaming spots and then happy to approve.

2024-04-29 04:16 UTC, ethanjohnsrud commented on src/widgets.tsx
> +                onPress={() => props.callback()}
Can we have a default behavior like `pop()` from the page stack?  Then `props.callback()` could be optional, but would override if provided.  If not possible and context is needed; then never mind.

2024-04-29 04:16 UTC, ethanjohnsrud commented on src/1-Profile/Edit-Profile.tsx
> +import PartnerSettings from '../4-Partners/Partnerships';
Can we also rename this import to `Partnerships`?

2024-04-29 04:16 UTC, ethanjohnsrud commented on src/App.tsx
> +import FirstSignIn from './1-Profile/InitianAccountFlow';
1. Can this import also be renamed to `InitialAccountFlow`?
2. And rename file to `InitialAccountFlow` too.

2024-04-29 04:16 UTC, ethanjohnsrud commented on src/TypesAndInterfaces/routes.tsx
> +    INITIAL_ACCOUNT_FLOW_ROUTE_NAME = "FirstSignIn"
Can this definition also be `"InitialAccountFlow"`?

2024-04-29 04:16 UTC, ethanjohnsrud commented on src/1-Profile/InitianAccountFlow.tsx
> +const FirstSignIn = ({navigation}:StackNavigationProps):JSX.Element => {
Can this component be renamed to `InitialAccountFlow` ?

2024-04-29 04:56 UTC, ethanjohnsrud approved these changes
Looks great, terrific work Josh!

2024-04-29 04:56 UTC, merged